### ISSUE TITLE
Curvelanes implementation

### ISSUE THREAD

**Issue by JiaweiZhao-git** [hirotomusiker/CLRerNet#19]
Good job. How do you implement the Curvelanes dataset training? I tried to convert Curvelanes format to Tusimple format and train with curvelane params, but the performance is much lower than reported.

**Comment by hirotomusiker** [comment]
For our paper, we implemented CLRerNet on Curvelanes based on CondlaneNet implementation.
config: https://github.com/aliyun/conditional-lane-detection/blob/master/configs/condlanenet/curvelanes/curvelanes_medium_train.py
data preparation: https://github.com/aliyun/conditional-lane-detection/blob/master/tools/condlanenet/curvelanes/prepare_curvelanes_datasets.py
dataset: https://github.com/aliyun/conditional-lane-detection/blob/master/mmdet/datasets/curvelanes_dataset.py
metrics: 
https://github.com/aliyun/conditional-lane-detection/blob/master/tools/condlanenet/lane_metric.py

And importantly if your model is anchor-based (like CLR(er)Net and LaneATT), don't forget to set the final NMS topk larger than 4 (e.g. 16) because Curvelanes has more lanes per image than CULane.

**Comment by VietPT3502** [comment]
can you provide your exact config in your experiments, i want to reproduce your  curvelanes result. For example: which nms topk did you use

**Comment by hirotomusiker** [comment]
OK we will add configs for Curvelanes soon. Thank you.

**Comment by hirotomusiker** [comment]
We have added the configs for CurveLanes.
https://github.com/hirotomusiker/CLRerNet/tree/tmp/curvelanes_config

Note that the following modules are necessary to train / test CurveLanes models but they are not ready on the above branch.
- CurvelanesDataset class
- Evaluation script (we use [condlanenet's metric script](https://github.com/aliyun/conditional-lane-detection/blob/master/tools/condlanenet/lane_metric.py) without modification)
- Dynamic `img_h` and `img_w` settings for LaneIoU ([Three crop settings are used for CurveLanes](https://github.com/aliyun/conditional-lane-detection/blob/master/mmdet/datasets/culane_dataset.py) depending on image sizes. LaneIoU needs the crop information.)
- Segmentation mask writer for aux. segmentation loss

**Comment by Onehundred0906** [comment]
@hirotomusiker thanks for your great work, can you share the mask generation code to the repo? because i reference the tusimple maks generation code and the F1-score is only up to 70? i think my mask is not precision.

**Comment by hirotomusiker** [comment]
Thank you.
The segmentation loss is auxiliary and contributes only slightly to the performance. Probably your training or inference code has issues other than that.

**Comment by Onehundred0906** [comment]
@hirotomusiker thanks for your reply, i have another question, because curve lanes have dense lines and 'Y' lines, and how to deal with these scenes in your paper? i think the nms is not suitable to deal with them, and perhaps i have some misunderstands, please help point out.

**Comment by hirotomusiker** [comment]
Thanks for your good question. We don't deal with Y lines like CondlaneNet does. We have just simply adapted CLRerNet to the dataset. Dealing with 'Y's will further improve the performance.

**Comment by hirotomusiker** [comment]
We have published the code for training on CurveLanes.
https://github.com/hirotomusiker/CLRerNet/tree/feature/curvelanes

`tmp/curvelanes_config` branch will be removed as the above branch includes the config file.
