### ISSUE TITLE
Question about Lane IoU implementation

### ISSUE THREAD

**Issue by VietPT3502** [hirotomusiker/CLRerNet#22]
i see that in your paper u said "For CULane dataset, we crop the input image below y = 270 and resize it to (800, 320) pixels"
but why in Lane IoU calculation, i see that u set default img_h=320, img_w=1640. And did you initialize prior exacly like CLRNet ?

**Comment by hirotomusiker** [comment]
We wanted to define the virtual lanes to calculated LaneIoU so that the width of the lanes are the same as the evaluation metric. The segmentation-based IoU calculation in the metric is done in (1640, 590) resolution.
https://github.com/hirotomusiker/CLRerNet/blob/main/libs/datasets/metrics/culane_metric.py#L22

As for prior initialization, we employ CLRNet's initial anchors. 
https://github.com/hirotomusiker/CLRerNet/blob/feature/train/libs/core/anchor/anchor_generator.py#L31

Thank you.

**Comment by VietPT3502** [comment]
thanks for fast reply <3. i want to ask 1 more question is that i see you set self.max_dx = 1e4. i want to ask what is this value and how do you find this?

**Comment by hirotomusiker** [comment]
The taget (GT) lanes have various lengths, and the rows where there are no lane labels (e.g. above the road) are set to -1e5.
https://github.com/hirotomusiker/CLRerNet/blob/ec392b95b8a076733bb879fc6b098e345a4d93f5/libs/datasets/pipelines/lane_formatting.py#L36-L38
So the following calculation should be very large value at the edge of the lane.
```
target_dx = (target[:, 2:] - target[:, :-2]) * self.img_w

target[0] : 
 9.6844e+00,  9.6848e+00, -2.0619e+05,  -2.0620e+05,  0.0000e+00,  0.0000e+00,
```

We suppress the large value like `-2.0620e+05` to zero to avoid erroneous target_width values.
`max_dx` can be set to a different value as long as it can filter the above large values.

We will add a comment on the `max_dx` part. Thank you.
