### ISSUE TITLE
image input size and video input

### ISSUE THREAD

**Issue by 10qiu01** [hirotomusiker/CLRerNet#49]
1.  I tried to process a screenshot of my video data, but the resulting image is very weird. I was wondering if there is any restrictions for input? By the way, did you use padding during resize or cropping the input image?

2. Do you have a mature pipeline for video data? 
Thanks in advance!!!

**Comment by hirotomusiker** [comment]
1: Could you refer to the following issue for cropping settings?
https://github.com/hirotomusiker/CLRerNet/issues/34

(1) Modify the [crop box](https://github.com/hirotomusiker/CLRerNet/blob/main/configs/clrernet/culane/dataset_culane_clrernet.py#L3)so that the coordinates [x0, y0, x1, y1] are within your input shape and the vanishing point is within the cropped window.
(2) Modify [test_cfg](https://github.com/hirotomusiker/CLRerNet/blob/main/configs/clrernet/base_clrernet.py#L76-L78) accordingly.

For example, if you wish to use (1920, 1080) format without cropping, it'd be like this:
```
crop_bbox = [0, 0, 1920, 1080]
test_cfg=dict(
...
    nms_topk=4,
    ori_img_w=1920,
    ori_img_h=1080,
    cut_height=0,
)
```

2. Please refer to the following issue.
 https://github.com/hirotomusiker/CLRerNet/issues/33
